name = "Scat"
uuid = "a8343a05-88f9-4e92-8017-218c44afd226"
authors = ["Jared Bryan"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
